---
apiVersion: v1
kind: Service
metadata:
  name: kvactest-service
spec:
  selector:
    app: kvactest
  ports:
  - port: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvactest
  labels:
    app: ex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex
  template:
    metadata:
      labels:
        app: ex
    spec:
      containers:
      - name: kvactest
        image: gjstevenson/kvactest:latest
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: personalcluster-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
         serviceName: kvactest-service
         servicePort: 80
        path: /